#!/usr/bin/env python3
"""
Docker Sync — 3-PC 환경 자동 설정 및 Docker 관리 유틸리티

PC 환경 자동 감지:
  - 집 PC   : D:/ai프로젝트 존재 여부 확인
  - 노트북  : whoami == info
  - 사무실  : whoami == 설계4

사용법:
    python scripts/docker_sync.py --setup    # PC 감지 → .env 자동 생성
    python scripts/docker_sync.py --start    # docker-compose up -d (core)
    python scripts/docker_sync.py --start --profile full   # 전체 서비스 기동
    python scripts/docker_sync.py --stop     # docker-compose down
    python scripts/docker_sync.py --status   # 실행 중인 서비스 상태 출력
    python scripts/docker_sync.py --logs     # 서비스 로그 스트리밍
"""

from __future__ import annotations

import argparse
import os
import platform
import shutil
import subprocess
import sys
from pathlib import Path

# ─────────────────────────────────────────────────────────────────────────────
# 경로 상수
# ─────────────────────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent.parent
DOCKER_DIR = REPO_ROOT / "docker"
ENV_EXAMPLE = DOCKER_DIR / ".env.example"
ENV_FILE = DOCKER_DIR / ".env"
COMPOSE_FILE = DOCKER_DIR / "docker-compose.yml"

# G드라이브 마운트 포인트 (Windows)
GDRIVE_PATH = "G:/내 드라이브"
VAULT_SUBPATH = "obsidian-agent-brain-system/ObsidianVault"

# PC별 로컬 AI 프로젝트 경로
PC_AI_PATHS: dict[str, str] = {
    "home":   "D:/ai프로젝트",
    "laptop": "C:/ai프로젝트",
    "office": "C:/ai프로젝트",
}

PC_LABELS: dict[str, str] = {
    "home":   "🏠 집 PC",
    "laptop": "💻 노트북",
    "office": "🏢 사무실 PC",
}


# ─────────────────────────────────────────────────────────────────────────────
# PC 환경 감지
# ─────────────────────────────────────────────────────────────────────────────

def detect_pc_env() -> str:
    """PC 환경을 자동 감지하여 'home' | 'laptop' | 'office' 반환."""
    # 1. 집 PC 판별: D:\ai프로젝트 존재 여부
    if Path("D:/ai프로젝트").exists():
        return "home"

    # 2. whoami 로 노트북 / 사무실 구분
    try:
        result = subprocess.run(
            ["whoami"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        username = result.stdout.strip().lower()
    except (subprocess.SubprocessError, FileNotFoundError):
        username = ""

    if "info" in username:
        return "laptop"
    if "설계4" in username or "xn--" in username:
        return "office"

    # 3. 환경변수 fallback
    env_val = os.environ.get("PC_ENV", "").lower()
    if env_val in ("home", "laptop", "office"):
        return env_val

    # 4. 사용자에게 물어보기
    print("PC 환경을 자동 감지하지 못했습니다.")
    choice = input("PC 환경을 선택하세요 [home/laptop/office]: ").strip().lower()
    if choice in ("home", "laptop", "office"):
        return choice

    print("기본값으로 'home'을 사용합니다.")
    return "home"


# ─────────────────────────────────────────────────────────────────────────────
# .env 파일 생성
# ─────────────────────────────────────────────────────────────────────────────

def build_env_content(pc_env: str) -> str:
    """PC 환경에 맞는 .env 파일 내용을 반환."""
    ai_path = PC_AI_PATHS[pc_env]
    vault_base = f"{GDRIVE_PATH}/{VAULT_SUBPATH}"

    lines: list[str] = [
        "# Auto-generated by docker_sync.py — do not commit this file",
        f"# PC: {PC_LABELS[pc_env]}",
        "",
        f"PC_ENV={pc_env}",
        "",
        "# 경로 설정",
        f"VAULT_BASE_PATH={vault_base}",
        f"LOCAL_AI_PATH={ai_path}",
        f"GDRIVE_PATH={GDRIVE_PATH}",
        "",
        "# API 키 (값은 직접 입력하세요)",
        "ANTHROPIC_API_KEY=",
        "DISCORD_BOT_TOKEN=",
        "GITHUB_TOKEN=",
        "",
        "# Discord 알림 (선택)",
        "DISCORD_WEBHOOK_URL=",
        "",
        "# 지식 정제기 설정",
        "DISTILLER_BATCH_SIZE=3",
        "DISTILLER_RETRY_MAX=3",
        "DISTILLER_INTERVAL_HOURS=6",
        "",
        "# Redis (AgentBus 상태 공유, 선택)",
        "REDIS_URL=redis://redis:6379/0",
        "",
        "# 로그 레벨",
        "LOG_LEVEL=INFO",
    ]
    return "\n".join(lines) + "\n"


def cmd_setup(args: argparse.Namespace) -> None:
    """PC 환경 감지 후 .env 파일 자동 생성."""
    pc_env = detect_pc_env()
    label = PC_LABELS[pc_env]
    ai_path = PC_AI_PATHS[pc_env]

    print(f"\n{label} 환경 감지되었습니다.")
    print(f"  - LOCAL_AI_PATH : {ai_path}")
    print(f"  - VAULT_BASE_PATH: {GDRIVE_PATH}/{VAULT_SUBPATH}")

    # 기존 .env 존재 시 백업
    if ENV_FILE.exists() and not args.force:
        backup = ENV_FILE.with_suffix(".env.bak")
        shutil.copy(ENV_FILE, backup)
        print(f"  - 기존 .env 백업: {backup}")

    env_content = build_env_content(pc_env)
    ENV_FILE.write_text(env_content, encoding="utf-8")
    print(f"\n.env 파일 생성 완료: {ENV_FILE}")
    print("\n다음 단계:")
    print("  1. docker/.env 에서 API 키 값을 입력하세요.")
    print("  2. python scripts/docker_sync.py --start")


# ─────────────────────────────────────────────────────────────────────────────
# docker-compose 래퍼
# ─────────────────────────────────────────────────────────────────────────────

def _compose(*compose_args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    """docker compose 명령을 DOCKER_DIR 에서 실행."""
    cmd = ["docker", "compose", "-f", str(COMPOSE_FILE), *compose_args]
    print(f"\n$ {' '.join(cmd)}")
    return subprocess.run(
        cmd,
        cwd=DOCKER_DIR,
        check=check,
        text=True,
    )


def _assert_env_exists() -> None:
    if not ENV_FILE.exists():
        print(f"[오류] {ENV_FILE} 파일이 없습니다.")
        print("먼저 'python scripts/docker_sync.py --setup' 을 실행하세요.")
        sys.exit(1)


def cmd_start(args: argparse.Namespace) -> None:
    """docker-compose up -d."""
    _assert_env_exists()

    compose_args = ["up", "-d", "--build"]

    # --profile 옵션
    profile = getattr(args, "profile", None)
    if profile:
        compose_args = ["--profile", profile] + compose_args

    _compose(*compose_args)
    print("\n서비스가 백그라운드에서 시작되었습니다.")
    print("상태 확인: python scripts/docker_sync.py --status")


def cmd_stop(args: argparse.Namespace) -> None:
    """docker-compose down."""
    _assert_env_exists()
    _compose("down")
    print("\n모든 서비스가 중단되었습니다.")


def cmd_status(args: argparse.Namespace) -> None:
    """docker-compose ps."""
    _assert_env_exists()
    _compose("ps", check=False)


def cmd_logs(args: argparse.Namespace) -> None:
    """docker-compose logs -f."""
    _assert_env_exists()
    service = getattr(args, "service", None)
    log_args = ["logs", "--follow", "--tail=100"]
    if service:
        log_args.append(service)
    try:
        _compose(*log_args)
    except KeyboardInterrupt:
        print("\n로그 스트리밍을 종료합니다.")


# ─────────────────────────────────────────────────────────────────────────────
# CLI
# ─────────────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="docker_sync.py",
        description="Bucky Brain — Docker 3-PC 동기화 환경 관리",
    )

    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--setup",  action="store_true", help="PC 감지 후 .env 자동 생성")
    group.add_argument("--start",  action="store_true", help="Docker 서비스 시작 (up -d)")
    group.add_argument("--stop",   action="store_true", help="Docker 서비스 중단 (down)")
    group.add_argument("--status", action="store_true", help="실행 중인 서비스 상태 확인")
    group.add_argument("--logs",   action="store_true", help="서비스 로그 스트리밍")

    parser.add_argument(
        "--profile",
        choices=["full", "distiller", "collector", "redis"],
        default=None,
        help="Docker Compose 프로파일 (--start 와 함께 사용)",
    )
    parser.add_argument(
        "--service",
        default=None,
        help="로그를 볼 특정 서비스 이름 (--logs 와 함께 사용)",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="기존 .env 파일을 덮어쓰기 (백업 없이)",
    )

    return parser.parse_args()


def main() -> None:
    args = parse_args()

    if not shutil.which("docker"):
        print("[오류] docker 명령을 찾을 수 없습니다. Docker Desktop이 설치 및 실행 중인지 확인하세요.")
        sys.exit(1)

    if args.setup:
        cmd_setup(args)
    elif args.start:
        cmd_start(args)
    elif args.stop:
        cmd_stop(args)
    elif args.status:
        cmd_status(args)
    elif args.logs:
        cmd_logs(args)


if __name__ == "__main__":
    main()
