#!/usr/bin/env python3
"""
Wishket 자동 제안서 생성기

Claude API를 사용해 공고에 맞는 맞춤형 제안서를 생성.
생성된 제안서는 Markdown으로 저장하고 Discord로 전송 가능.
"""

import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

_ROOT = Path(__file__).parent.parent
PROPOSALS_DIR = _ROOT / "ObsidianVault" / "10_AgentBus" / "wishket_proposals"
PROPOSALS_DIR.mkdir(parents=True, exist_ok=True)

# 프리랜서 프로필 (환경변수 또는 기본값)
FREELANCER_PROFILE = {
    "name": os.getenv("FREELANCER_NAME", "개발자"),
    "skills": os.getenv(
        "FREELANCER_SKILLS",
        "Python, FastAPI, Discord 봇, AI/Claude API 연동, 자동화, 웹 스크래핑, 데이터 파이프라인",
    ),
    "experience": os.getenv("FREELANCER_EXPERIENCE", "5년 이상"),
    "portfolio": os.getenv("FREELANCER_PORTFOLIO", ""),
    "contact": os.getenv("FREELANCER_CONTACT", ""),
}

PROPOSAL_SYSTEM_PROMPT = """당신은 프리랜서 개발자입니다. Wishket 플랫폼에서 프로젝트 수주를 위한
설득력 있는 제안서를 작성합니다.

제안서 작성 원칙:
1. 첫 문장에 핵심 가치 제안 (고객이 왜 나를 선택해야 하는지)
2. 공고의 핵심 요구사항 3가지 명시 후 각각 어떻게 해결할지 서술
3. 구체적인 기술 스택과 접근 방법 제시
4. 예상 일정과 마일스톤 (간략히)
5. 마무리: 빠른 시작 가능 여부 + 연락 요청

분량: 400~600자 (너무 길면 안 읽음)
톤: 전문적이고 자신감 있되, 과장 없이"""

PROPOSAL_USER_TEMPLATE = """다음 프로젝트에 대한 제안서를 작성해주세요:

## 프로젝트 정보
제목: {title}
예산: {budget}
설명: {description}

## 나의 프로필
이름/닉네임: {name}
보유 기술: {skills}
경력: {experience}
포트폴리오: {portfolio}

제안서를 한국어로 작성해주세요."""


def generate_proposal_via_claude(project: dict) -> str:
    """Claude CLI를 통해 제안서 생성."""
    user_prompt = PROPOSAL_USER_TEMPLATE.format(
        title=project.get("title", ""),
        budget=project.get("budget", "미정"),
        description=project.get("description", "설명 없음"),
        name=FREELANCER_PROFILE["name"],
        skills=FREELANCER_PROFILE["skills"],
        experience=FREELANCER_PROFILE["experience"],
        portfolio=FREELANCER_PROFILE["portfolio"] or "요청 시 제공",
    )

    full_prompt = f"{PROPOSAL_SYSTEM_PROMPT}\n\n{user_prompt}"

    env = os.environ.copy()
    env["BUCKY_SUBPROCESS"] = "1"
    claude_cmd = os.getenv("CLAUDE_COMMAND", "claude")

    try:
        result = subprocess.run(
            [claude_cmd, "--dangerously-skip-permissions", "-p", full_prompt],
            capture_output=True,
            text=True,
            encoding="utf-8",
            errors="replace",
            timeout=60,
            env=env,
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout.strip()
        return f"[생성 실패] {result.stderr[:200]}"
    except Exception as e:
        return f"[생성 오류] {e}"


def save_proposal(project: dict, proposal_text: str) -> Path:
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe_title = "".join(c for c in project.get("title", "unknown")[:30] if c.isalnum() or c in " _-").strip()
    filename = f"{ts}_{safe_title}.md"
    out = PROPOSALS_DIR / filename

    content = f"""# 제안서: {project.get('title', '')}

**작성일**: {datetime.now().strftime('%Y-%m-%d %H:%M')}
**프로젝트 링크**: {project.get('link', '')}
**예산**: {project.get('budget', '미정')}

---

{proposal_text}

---
*Generated by Bucky Wishket Agent*
"""
    out.write_text(content, encoding="utf-8")
    print(f"[Proposal] 저장: {out}")
    return out


def generate_proposals(projects: list[dict]) -> list[dict]:
    """공고 목록에 대해 제안서 일괄 생성."""
    results = []
    for i, project in enumerate(projects):
        print(f"[Proposal] {i+1}/{len(projects)} 생성 중: {project.get('title', '')[:40]}")
        proposal_text = generate_proposal_via_claude(project)
        path = save_proposal(project, proposal_text)
        results.append(
            {
                "project": project,
                "proposal": proposal_text,
                "file": str(path),
                "generated_at": datetime.now().isoformat(),
            }
        )

    return results


def run(projects: list[dict] | None = None) -> list[dict]:
    """메인 실행: 공고 목록이 없으면 최신 스크래핑 결과 사용."""
    if projects is None:
        inbox = _ROOT / "ObsidianVault" / "10_AgentBus" / "wishket_inbox"
        files = sorted(inbox.glob("wishket_*.json"), reverse=True)
        if not files:
            print("[Proposal] 수집된 공고 없음. 먼저 wishket_scraper.py 실행")
            return []
        projects = json.loads(files[0].read_text(encoding="utf-8"))
        print(f"[Proposal] {files[0].name}에서 {len(projects)}개 공고 로드")

    return generate_proposals(projects)


if __name__ == "__main__":
    results = run()
    print(f"\n제안서 생성 완료: {len(results)}개")
    for r in results:
        print(f"  - {r['project']['title'][:40]} → {Path(r['file']).name}")
